---
title: Publications

comments: false

---

## Selected Journal Articles
[10] 2025. [The Institutional Impact of Left-Leaning Populism in Latin America][P60]  
**European Journal of Political Economy**  
Nicolas Cachanosky | [João P. Bastos][JPB] | [Alexandre Padilla][AP] | Karla C. Hernández  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5005108" class="button-link">SSRN version</a>

[09] 2022. [Can Dollarization Constrain a Populist Leader? The Case of Rafael Correa in Ecuador][P53]  
**Journal of Economic Behavior and Organization**, Vol. 200 (August), pp. 430-442.  
DOI: 10.1016/j.jebo.2022.06.006  
Nicolas Cachanosky | [Alexander W. Salter][AS] | Ignacio Savanti  
<a href="https://papers.ssrn.com/abstract=3988413" class="button-link">SSRN version</a>

[08] 2021. [The Federal Reserve's Response to the Covid-19 Contraction: An Initial Appraisal][P49]  
**Southern Economic Journal**, Vol. 87, No. 4, pp. 1152-1174    
DOI: 10.1002/soej.12498  
Nicolas Cachanosky | [Bryan P. Cutsinger][BC] | [Thomas L. Hogan][TH] | [William J. Luther][WL] | [Alexander W. Salter][AS]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3726345" class="button-link">SSRN version</a>

[07] 2021. [Immigration and Institutional Change: Did Mass Immigration Cause Peronism in Argentina?][P48]  
**Journal of Economic Behavior and Organization**, Vol. 184 (April), pp. 1-15  
DOI: 10.1016/j.jebo.2021.01.027  
Nicolas Cachanosky | [Alexandre Padilla][AP] | [Alejandro O. Gomez][AG]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3764194" class="button-link">SSRN version</a>

[06] 2021. [Why Did Inflation Targeting Fail in Argentina?][P47]  
**Quarterly Review of Economics and Finance**, Vol. 80 (May), pp. 102-116  
DOI: 10.1016/j.qref.2021.01.014  
Nicolas Cachanosky | Federico Julián Ferrelli Mazza  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3384731" class="button-link">SSRN version</a>

[05] 2018. [The Average Period of Production: History of an Idea][P33]  
**Journal of the History of Economic Thought**, Vol. 40, No.1, pp. 81-98  
DOI: 10.1017/S105383721700013X  
[Peter Lewin][PL] | Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2479408" class="button-link">SSRN version</a>

[04] 2018. [The Grecian Horse: Does Immigration Lead to the Deterioration of American Institutions?][P32]  
**Public Choice**, Vol. 30, No. 2, pp. 169-192  
DOI: 10.1007/s11127-018-0509-5  
[Alexandre Padilla][AP] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2972345" class="button-link">SSRN version</a>

[03] 2016. [Ludwig von Mises's Approach to Capital as a Bridge Between Austrian and Institutional Economics][P24]  
**Journal of Institutional Economics**, Vol. 12, No. 4, pp. 847-866  
DOI: 10.1017/S1744137416000102  
[Eduard Brown][EB] | [Peter Lewin][PL] | Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2748937" class="button-link">SSRN version</a>

[02] 2016. [An Empirical Application of the EVA Framework to Business Cycles][P23]  
**Review of Financial Economics**, Vol. 30 (september), pp. 60-67  
DOI: 10.1016/j.rfe.2016.06.006  
Nicolas Cachanosky | [Peter Lewin][PL]  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2628912" class="button-link">SSRN version</a>

[01] 2015. [Implications of Machlup's Interpretation of Mises's Epistemology][P14]  
**Journal of the History of Economic Thought**, Vol. 37, No. 1, pp. 111-138  
DOI: 10.1017/S1053837214000777  
[Gabriel J. Zanotti][GZ] | Nicolas Cachanosky  
<a href="http://papers.ssrn.com/abstract=2229570" class="button-link">SSRN version</a>

## All Journal Articles

[63] *Forthcoming.* A Lakatosian and Non-conventionalist Reconstruction of Mises  
**The Review of Austrian Economics**  
[Gabriel J. Zanotti][GZ] | Agustina Borella | Nicolas Cachanosky  
DOI: 0.1007/s11138-025-00681-7  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5241224" class="button-link">SSRN version</a>  

[62] *Forthcoming.* The Political Economy of Populism Regime Length  
**Constitutional Political Economy**  
[João P. Bastos][JPB] | Nicolas Cachanosky | Tomás Faintich  
DOI: 10.1007/s10602-025-09465-4  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4445116" class="button-link">SSRN version</a>

[61] 2025. [Classical Liberalism in Argentina, from 1884 to 2023][P61]  
**Econ Journal Watch**, Vol. 22, Issue 1, pp. 415-436.  
Alejandro Gómez | Nicolas Cachanosky  

[60] 2025. [The Institutional Impact of Left-Leaning Populism in Latin America][P60]  
**European Journal of Political Economy**, Vol. 86, pp. 1-26.  
Nicolas Cachanosky | [João P. Bastos][JPB] | [Alexandre Padilla][AP] | Karla C. Hernández  
DOI: 10.1016/j.ejpoleco.2024.102629  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5005108" class="button-link">SSRN version</a>

[59] 2025. [Did Dollarization Help Ecuador?][P59]  
**Scottish Journal of Political Economy**, Vol. 72, No. 1, pp. 1-11  
Nicolas Cachanosky | [Emilio Ocampo][EO] | Karla C. Hernández | John Ramseur  
DOI: 10.1111/sjpe.12397  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3678055" class="button-link">SSRN version</a>

[58] 2024. [Classical Liberalism in Argentina, from 1816 to 1884][P58]  
**Econ Journal Watch**, Vol. 21, Issue 1, pp. 415-436.  
Alejandro Gómez | Nicolas Cachanosky  

[57] 2023. [Hermeneutics and Phenomenology in the Social Sciences: Lessons from the Austrian School of Economics Case][P57]  
**The Review of Austrian Economics**, Vol. 36, No. 3, pp. 403-415.  
[Gabriel J. Zanotti][GZ] | Agustina Borella | Nicolas Cachanosky  
DOI: 10.1007/s11138-021-00548-7  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3596226" class="button-link">SSRN version</a>

[56] 2023. [Lessons From Dollarization in Latin America in the 21st Century][P56]  
**The Economists' Voice**, Vol. 20, No. 1, pp. 25-42.  
DOI: 10.1515/ev-2023-0001  
Nicolas Cachanosky | [Emilio Ocampo][EO] | [Alexander W. Salter][AS]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4318258" class="button-link">SSRN version</a>

[55] 2023. [Immigration and Economic Freedom of the US States:  Does the Institutional Quality of Immigrants’ Origin Countries Matter?][P55]  
**Contemporary Economic Policy**, Vol. 41, No. 3, pp. 489-512.  
[Alexandre Padilla][AP] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3316415" class="button-link">SSRN version</a>

[54] 2022. [Monetary Disorder in Buenos Aires Province (1822-1881)][P54]  
**The Independent Review**, Vol. 27, No. 1, pp. 23-35.  
[Adrián O. Ravier][AR] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3753634" class="button-link">SSRN version</a>

[53] 2022. [Can Dollarization Constrain a Populist Leader? The Case of Rafael Correa in Ecuador][P53]  
**Journal of Economic Behavior and Organization**, Vol. 200 (August), pp. 430-442.  
Nicolas Cachanosky | [Alexander W. Salter][AS] | Ignacio Savanti  
<a href="https://papers.ssrn.com/abstract=3988413" class="button-link">SSRN version</a>

[52] 2022. [The Upper Turning Point in the Austrian Business Cycle Theory][P52]  
**The Review of Austrian Economics**, Vol. 35, No. 1, pp. 89-97  
DOI: 10.1007/s11138-019-00497-2  
[Anthony J. Evans][AV] | Nicolas Cachanosky | Robert Thorpe  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3145284" class="button-link">SSRN version</a>

[51] 2021. [Latin America Left-Populism, Price of Commodities, and Economic Crises][P51]  
**Journal of Private Enterprise Education**, Vol. 36, No. 2, pp. 1-17.  
Nicolas Cachanosky | [Alexandre Padilla][AP]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3375424" class="button-link">SSRN version</a>

[50] 2021. [Microfoundations and Macroeconomics: 20 Years][P50]  
**The Review of Austrian Economics**, Vol.34, No. 2, pp. 279-288  
Nicolas Cachanosky  
DOI: 10.1007/s11138-020-00500-1  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3569069" class="button-link">SSRN version</a>

[49] 2021. [The Federal Reserve's Response to the Covid-19 Contraction: An Initial Appraisal][P49]  
**Southern Economic Journal**, Vol. 87, No. 4, pp. 1152-1174  
DOI: 10.1002/soej.12498  
Nicolas Cachanosky | [Bryan P. Cutsinger][BC] | [Thomas L. Hogan][TH] | [William J. Luther][WL] | [Alexander W. Salter][AS]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3726345" class="button-link">SSRN version</a>

[48] 2021. [Immigration and Institutional Change: Did Mass Immigration Cause Peronism in Argentina?][P48]  
**Journal of Economic Behavior and Organization**, Vol. 184 (April), pp. 1-15  
DOI: 10.1016/j.jebo.2021.01.027  
Nicolas Cachanosky | [Alexandre Padilla][AP] | [Alejandro O. Gomez][AG]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3764194" class="button-link">SSRN version</a>

[47] 2021. [Why Did Inflation Targeting Fail in Argentina?][P47]  
**Quarterly Review of Economics and Finance**, Vol. 80 (May), pp. 102-116  
DOI: 10.1016/j.qref.2021.01.014  
Nicolas Cachanosky | Federico Julián Ferrelli Mazza  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3384731" class="button-link">SSRN version</a>

[46] 2020. [A Panel Data Analysis of Latin American Populism][P46]  
**Constitutional Political Economy**, Vol. 31, No. 3, pp. 321-343  
DOI: 10.1007/s10602-020-09302-w  
Nicolas Cachanosky | [Alexandre Padilla][AP]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3304356" class="button-link">SSRN version</a> <a href="https://data.mendeley.com/datasets/rf85cmv527/1" class="button-link">data</a>

[45] 2020. [Immigration and Economic Freedom: Does Education Matter?][P45]  
**The Journal of Private Enterprise**, Vol. 35, No. 1, pp. 29-57  
[Alexandre Padilla][AP] | Nicolas Cachanosky | Jonathan Beck  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3396748" class="button-link">SSRN version</a>

[44] 2020. [Rediscovering Buchanan's Rediscovery: Non-Market Exchange versus Antiseptic Allocation][P44]  
**Public Choice**, Vol. 183, No. 3-4, pp. 461-477  
DOI: 10.1007/s11127-020-00819-0  
Nicolas Cachanosky | [Edward J. Lopez][EJL]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3565167" class="button-link">SSRN version</a>

[43] 2020. [Entrepreneurship in a Theory of Capital and Finance: Illustrating the Use of Subjective Quantification][P43]  
**Managerial and Decision Economics**, Vol. 41, No. 5, pp. 735-743  
DOI: 10.1002/mde.3133  
[Peter Lewin][PL] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3514865" class="button-link">SSRN version</a>

[42] 2020. [The Super-Alertness of Central Banks][P42]  
**The Review of Austrian Economics**, Vol. 33, No. 1-2, pp. 187-200  
DOI: 10.1007/s11138-019-00436-1  
Nicolas Cachanosky | [Alexander W. Salter][AS]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3329356" class="button-link">SSRN version</a>

[41] 2020. [Immigration, Economic Freedom, and Ideology][P41]  
**The International Trade Journal**, Vol. 34, No. 1, pp. 5-17  
DOI: 10.1080/08853908.2019.1695026  
[Alexandre Padilla][AP] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3402671" class="button-link">SSRN version</a>

[40] 2019. [Can Bitcoin Become Money? The Monetary Rule Problem][P40]  
**Australian Economic Papers**, Vol. 58, No. 4, pp. 365-374  
DOI: 10.1111/1467-8454.12158  
Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3124359" class="button-link">SSRN version</a>

[39] 2019. [Re-switching, the Average Period of Production and the Austrian Business Cycle Theory: A Comment on Fratini][P39]  
**The Review of Austrian Economics**, Vol. 32, No. 4, pp. 375-382  
DOI: 10.1007/s11138-019-00460-1  
[Peter Lewin][PL] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3386843" class="button-link">SSRN version</a>

[38] 2019. [Latin American Populism in the 21st Century][P38]  
**The Independent Review**, Vol. 42, No. 2, pp. 209-226  
Nicolas Cachanosky | [Alexandre Padilla][AP]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3147096" class="button-link">SSRN version</a>

[37] 2018. [The Cost of Populism in Argentina, 2002-2015][P37]  
**MISES: Interdisciplinary Journal in Philosophy, Law and Economics** (special issue)  
Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3249775" class="button-link">SSRN version</a>

[36] 2018. [The Role of Capital Structure in Austrian Business Cycle Theory][P36]  
**The Journal of Private Enterprise**, Vol. 33, No. 2, pp. 21-32  
Nicolas Cachanosky | [Peter Lewin][PL]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2957887" class="button-link">SSRN version</a>

[35] 2018. [Substance and Semantics: The Question of Capital][P35]  
**Journal of Economic Behavior and Organization**, Vol. 150, No. 4, pp, 423-432  
DOI: 10.1016/j.jebo.2018.01.024  
[Peter Lewin][PL] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2613469" class="button-link">SSRN version</a>

[34] 2018. [Value and Capital: Austrian Capital Theory, Retrospect and Prospect][P34]  
**The Review of Austrian Economics**, Vol. 31, No. 1, pp. 1-26  
DOI: 10.1007/s11138-016-0374-8  
[Peter Lewin][PL] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2866019" class="button-link">SSRN version</a>

[33] 2018. [The Average Period of Production: History of an Idea][P33]  
**Journal of the History of Economic Thought**, Vol. 40, No.1, pp. 81-98  
DOI: 10.1017/S105383721700013X  
[Peter Lewin][PL] | Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2479408" class="button-link">SSRN version</a>

[32] 2018. [The Grecian Horse: Does Immigration Lead to the Deterioration of American Institutions?][P32]  
**Public Choice**, Vol. 30, No. 2, pp. 169-192  
DOI: 10.1007/s11127-018-0509-5  
[Alexandre Padilla][AP] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2972345" class="button-link">SSRN version</a>

[31] 2017. [Secular Growth in Garrison's Model: A Comment][P31]  
**The Quarterly Journal of Austrian Economics**, Vol. 40, No. 5, pp. 354-359  
Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3080507" class="button-link">SSRN version</a>

[30] 2017. [Entrepreneurship and Bitcoin: Breaking the Network Effect][P30]  
**The Review of Austrian Economics**, Vol. 30, No. 3, pp. 263-275  
DOI: 10.1007/s11138-016-0348-x  
[Malavika Nair][MN] | Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2799479" class="button-link">SSRN version</a>

[29] 2017. [Austrian Economics, Market Process, and the EVA Framework][P29]  
**Journal of Business Valuation and Economic Loss Analysis**, Vol. 12 (s1)  
DOI: 10.1515/jbvela-2016-0014  
Nicolas Cachanosky
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2799501" class="button-link">SSRN version</a>

[28] 2017. [The Myth of the Natural Resource Curse: A Case Study for Algeria][P28]  
**The Journal of Private Enterprise**, Vol. 32, No. 2, pp. 1-15  
Mohammed Akacem | Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2633793" class="button-link">SSRN version</a>

[27] 2017. [The View from Vienna: An Analysis of the Renewed Interest in the Mises-Hayek Theory of Business Cycles][P27]  
**The Review of Austrian Economics**, Vol. 30, No. 2, pp. 169-192  
DOI: 10.1007/s11138-016-0340-5  
Nicolas Cachanosky | [Alexander W. Salter][AS]  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2363560" class="button-link">SSRN version</a>

[26] 2017. [A Mathematical Version of Garrison's Model][P26]  
**The Quarterly Journal of Austrian Economics**, Vol. 19, No. 3, pp. 225-247  
Nicolas Cachanosky | [Alexandre Padilla][AP]  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2830938" class="button-link">SSRN version</a>

[25] 2016. Offsetting and Sterilization Mechanisms in Argentina (1992-2014)  
**Credit and Capital Markets**, Vol. 49, No. 4, pp. 515-534  
Nicolas Cachanosky | Carolyn Thomas  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2832884" class="button-link">SSRN version</a>

[24] 2016. [Ludwig von Mises's Approach to Capital as a Bridge Between Austrian and Institutional Economics][P24]  
**Journal of Institutional Economics**, Vol. 12, No. 4, pp. 847-866  
DOI: 10.1017/S1744137416000102  
[Eduard Brown][EB] | [Peter Lewin][PL] | Nicolas Cachanosky   
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2748937" class="button-link">SSRN version</a>

[23] 2016. [An Empirical Application of the EVA Framework to Business Cycles][P23]  
**Review of Financial Economics**, Vol. 30 (September), pp. 60-67  
DOI: 10.1016/j.rfe.2016.06.006  
Nicolas Cachanosky | [Peter Lewin][PL]  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2628912" class="button-link">SSRN version</a>

[22] 2016. [Indirectly Productive Entrepreneurship][P22]  
**Journal of Entrepreneurship and Public Policy**, Vol. 5, No. 2, pp. 161-175  
DOI: 10.1108/JEEP-03-2015-0016  
[Alexandre Padilla][AP] | Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2584741" class="button-link">SSRN version</a>

[21] 2016. [Financial Framework for Understanding Macroeconomic Cycles: The Time Structure of Production is Relevant][P21]  
**Journal of Financial Economic Policy**, Vol. 8, No. 2, pp. 268-280  
DOI: 10.1108/JFEP-07-2015-0041  
[Peter Lewin][PL] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2443591" class="button-link">SSRN version</a>

[20] 2016. [Financial Foundations of Austrian Business Cycle Theory][p20]  
**Advances in Austrian Economics**, Vol. 20, pp. 15-44  
DOI: 10.1108/S1529-213420160000020002  
Nicolas Cachanosky | [Peter Lewin][PL]  
<a href="http://papers.ssrn.com/abstract=2456766" class="button-link">SSRN version</a>

[19] 2016. [Argentina's Post 2001 Economy and the 2014 Default][P19]  
**The Quarterly Review of Economics and Finance**, Vol. 60 (May), pp. 70-80  
DOI: 10.1016/j.qref.2015.08.002  
Nicolas Cachanosky | Carolyn Thomas  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2579438" class="button-link">SSRN version</a>

[18] 2016. [Monetary Policy, the Composition of GDP, and Crisis Duration in Europe][p18]  
**Global Economic Review**, Vol. 45, No. 2, pp. 206-219  
DOI: 10.1080/1226508X.2015.1137484  
[Andreas Hoffmann][AH] | Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2709192" class="button-link">SSRN version</a>

[17] 2015. [Fiscal Policy and Crowding Out Effects in Capital Based Macroeconomics with Idle Resources][P17]  
**The Journal of Private Enterprise**, Vol. 30, No. 4, pp. 81-95  
[Adrián O. Ravier][AR] | Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2487615" class="button-link">SSRN version</a>

[16] 2015. [U.S. Monetary Policy's Impact on Latin America's Structure of Production (1960-2010)][P16]  
**Latin American Journal of Economics**, Vol. 52, No.1, pp. 95-116  
DOI: 10.7764/LAJE.52.1.95  
Nicolas Cachanosky
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2248413" class="button-link">SSRN version</a>

[15] 2015. [Expectations in Austrian Business Cycle Theory: Market Share Matters][P15]  
**The Review of Austrian Economics**, Vol. 28, No. 2, pp. 151-165  
DOI: 10.1007/s11138-014-0267-7  
Nicolas Cachanosky
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2025666" class="button-link">SSRN version</a>

[14] 2015. [Implications of Machlup's Interpretation of Mises's Epistemology][P14]  
**Journal of the History of Economic Thought**, Vol. 37, No. 1, pp. 111-138  
DOI: 10.1017/S1053837214000777  
[Gabriel J. Zanotti][GZ] | Nicolas Cachanosky  
<a href="http://papers.ssrn.com/abstract=2229570" class="button-link">SSRN version</a>

[13] 2015. [A Proposal of Monetary Reform for Argentina: Flexible Dollarization and Free Banking][P13]  
**The Independent Review**, Vol. 19, No. 3, pp. 397-426  
Nicolas Cachanosky | [Adrián O. Ravier][AR]  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2378541" class="button-link">SSRN version</a>

[12] 2014. [Roundaboutness is not a Mysterious Concept: A Financial Application to Capital Theory][P12]  
**The Review of Political Economy**, Vol. 24, No. 6, pp. 648-665  
DOI: 10.1080/09538259.2014.957475  
Nicolas Cachanosky | [Peter Lewin][PL]  
<a href="http://papers.ssrn.com/abstract=2411022" class="button-link">SSRN version</a>

[11] 2014 [The Mises-Hayek Business Cycle Theory, Fiat Currencies, and Open Economies][P11]  
**The Review of Austrian Economics**, Vol. 27, no. 3, pp. 281-299  
DOI: 10.1007/s11138-012-0188-2  
Nicolas Cachanosky  
<a href="http://papers.ssrn.com/abstract=2015456" class="button-link">SSRN version</a>

[10] 2014. [The Effects of U.S. Monetary Policy in Colombia and Panama (2002-2007)][P10]  
**The Quarterly Review of Economics and Finance**, Vol. 53, No. 3, pp. 428-436  
DOI: 10.1016/j.qref.2014.03.003  
Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2170566" class="button-link">SSRN version</a>

[09] 2014. [Hayek's Rule, NGDP Targeting, and the Productivity Norm: Theory and Application][P09]  
**Journal of Stock & Forex Trading**, Vol. 3, No. 2, pp. 1-9   
DOI: 10.4172/2168-9458.1000121  
Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2373230" class="button-link">SSRN version</a>

[08] 2013. [Huerta de Soto's Concerted Expansion: A Prisoner's Dilemma in Free Banking?][P08]  
**Laissez-Faire**, Vol. 38-39, pp. 1-6  
Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1749689" class="button-link">SSRN version</a>

[07] 2012. [Mises on Fractional Reserves: A Review of Huerta de Soto's Argument][P07]  
**New Perspectives on Political Economy**, Vol. 7, No. 2, pp. 203-230  
Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1734143" class="button-link">SSRN version</a>

[06] 2012. [The Law of National Guaranteed Banks in Argentina (1887-1890): Free Banking Failre or Regulatory Failure?][P06]  
**The Independent Review**, Vol. 16, No. 4, pp. 569-590  
Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1802046" class="button-link">SSRN version</a>

[05] 2011. [A Comment on Barnett and Block on Time Deposit and Bagus and Howden on Loan Maturity Mismatching][P05]  
**Journal of Business Ethics**, Vol. 104, No. 2, pp. 219-221  
DOI: 10.1007/s10551-011-0900-3  
Nicolas Cachanosky  
<a href="http://papers.ssrn.com/abstract=1751245" class="button-link">SSRN version</a>

[04] 2011. [Calculation and Equilibrium Problems in Coase Theorem][P04]  
**Quarterly Journal of Austrian Economics**, Vol. 14, No. 1, pp. 63-77  
Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1855326" class="button-link">SSRN version</a>

[03] 2010. [The Endogenous Stability of Free Banking: Crisis as an Exogenous Phenomenon][P03]  
**New Perspectives on Political Economy**, Vol. 6, No. 1, pp, 31-48  
Nicolas Cachanosky  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1749703" class="button-link">SSRN version</a>

[02] 2010. [The Austrian School and Game Theory: An Analysis of Spontaneous Orders][P02]  
**Revista de Instituciones, Ideas y Mercados**, No. 52, pp. 52-58  
Nicolas Cachanosky  

[01] 2009. [The Definition of Inflation According to Mises: Implications for the Debate on Free Banking][P01]  
**Libertarian Papers**, Vol. 1, No. 9, pp. 1-7  
<a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1749785" class="button-link">SSRN version</a>
Nicolas Cachanosky  


## Non-Refereed Journal Articles
[07] 2021. [The Austrian School: 150 Years][NRP07]  
**LIBERTAS: Segunda Época**, Vol. 6, No. 1, pp. 1-11  
Nicolas Cachanosky  

[06] 2021. [Capital: Three-Dimensionally Speaking][NRP06]  
**LIBERTAS: Segunda Época**, Vol. 6, No. 1, pp. 1-11  
[Peter Lewin][PL] | Nicolas Cachanosky  

[05] 2019. [What is so Extreme About Mises's Extreme Apriorism: Reply to Scott Scheall][NRP05]  
**LIBERTAS: Segunda Época**, Vol. 4, No. 1, pp. 1-6  
[Gabriel J. Zanotti][GZ] | Nicolas Cachanosky

[04] 2017. [Economic and Philosophical Implications of Hayek's Knowledge Problem][NRP04]  
**LIBERTAS: Segunda Época**, Vol. 2, No. 1, pp. 67-79  
Nicolas Cachanosky | [Alexandre Padilla][AP]

[03] 2017. [Monetary Policy in India and the U.S.: Is the Taylor Rule Relevant?][NRP03]  
**International Review of Business & Eonomics**, Vol. 1, No. 1  
Bansi Sawhney | Kishore Kulkarni | Nicolas Cachanosky

[02] 2016. [La Matemática y la Tradición Austriaca: Respuesta a Rafael Beltramino][NRP02]  
**LIBERTAS: Segunda Época**, Vol. 1, No. 2, pp. 95-103  
Nicolas Cachanosky

[01] 2016. [Problemas Matemáticos en la Teoría de Precios][NRP01]  
**LIBERTAS: Segunda Época**, Vol. 1, No. 1, pp. 11-27  
Juan C. Cachanosky | Nicolas Cachanosky  


## Book Chapters

[10] *Forthcoming*. Hayek's Two Epistemologies: Economics and Sciences in General  
In Candela, R. (ed.) **UFM Companion to F. A. Hayek**.  
[Gabriel J. Zanotti][GZ] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3176778" class="button-link">SSRN version</a>

[09] *Forthcoming*. Hayek's Average Period of Production: A Step Forward and a Missed Opportunity  
In Candela, R. (ed.) **UFM Companion to F. A. Hayek**  
Nicolas Cachanosky | [Peter Lewin][PL]  
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3132653" class="button-link">SSRN version</a>

[08] 2023. [Accounting and Finance: Capital and Cost in Economics][BC08]  
In Horwitz, S., and Rouanet, L. (eds.) **A Research Agenda for Austrian Economics**  
[Peter Lewin][PL] | Nicolas Cachanosky  
<a href="https://papers.ssrn.com/abstract=3848142" class="button-link">SSRN version</a>

[07] 2022. [Can Cryptocurrencies become a Commonly Accepted Means of exchange?][BC07]  
In Caton, J. (ed.) **The Economics of Blockchain and Cryptocurrency**.  
Nicolas Cachanosky  
<a href="https://papers.ssrn.com/abstract=3660521" class="button-link">SSRN version</a>

[06] 2022. [Capital Theory and the Theory of the Firm](https://www.e-elgar.com/shop/gbp/a-modern-guide-to-austrian-economics-9781789904390.html)  
In Bylund, P. (ed.) **Modern Guide to Austrian Economics**.  
[Peter Lewin][PL] | Nicolas Cachanosky 

[05] 2018. [Unintended Consequences of ECB Policies in Europe's Periphery][BC05]  
In Godart-van der Kroon, A., and Volanthen, P. (eds.) **Banking and Monetary Policy from the Perspective of Austrian Economics**. Springer  
[Andreas Hoffmann][AH] | Nicolas Cachanosky

[04] 2017. El Deterioro Económico de Argentina Durante el Gobierno Kirchner-Kirchner  
In Arqueros, C. and Iriarte, A. (eds.) **Chile y América Latina: Crisis de las Izquierdas del Siglo XXI**. Chile: Instituto Res República and Instituto del Desarrollo  
Nicolas Cachanosky

[03] 2017. [Economic Value Added: Una Aplicación Financiera al Análisis Económico][BC03]  
In Giménez Bonet, W., and Tournisov, A. (eds.) **Libertad y Convicciones: Ensayos en Honor al Dr. Juan Carlos Cachanosky**, Chapter 3. Guatemala: Editorial Episteme.  
Nicolas Cachanosky  

[02] 2015. [Employment VISAs: An International Comparison][BC02]  
In Powell, B. (ed.) **The Economics of Immigration: Market-Based Approaches, Social Science, and Public Policy**, Chapter 5, pp. 92-142. Oxford: Oxford University Press.  
[Alexandre Padilla][AP] | Nicolas Cachanosky

[01] 2012. [Una Introducción a la Economía Clásica][BC01]  
In Ravier, A. (ed.) **Lecturas de Historia del Pensamiento Económico**. Madrid: Unión Editorial. Chapter VIII, pp. 147-166  
Nicolas Cachanosky  

---
## Working Papers
[04] 2024. [Conflict Theories of Inflation: A Note][WP04]  
C4FE Working Paper Series 2024/06  
Nicolas Cachanosky | [Emilio Ocampo][EO]  

[03] 2024. [Dollarization and Default Risk: A Brief Note][WP03]  
C4FE Working Paper Series 2024/06  
[Emilio Ocampo][EO] | Nicolas Cachanosky

[02] 2023. [Dollarization Dynamics: A Comment][WP02]  
C4FE Working Paper Series 2024/02
[Emilio Ocampo][EO] | Nicolas Cachanosky

[01] 2023. [Is Inflation Caused by Conflict][WP01]  
C4FE Working Paper Series 2024/01
Nicolas Cachanosky | [Emilio Ocampo][EO]


<!-- HYPERLINKS TO JOURNAL ARTICLES -->
[P61]: <https://econjwatch.org/articles/classical-liberalism-in-argentina-1884-to-2023>

[P60]: <https://doi.org/10.1016/j.ejpoleco.2024.102629>

[P59]: <https://onlinelibrary.wiley.com/doi/10.1111/sjpe.12397>

[P58]: <https://econjwatch.org/articles/classical-liberalism-in-argentina-from-1816-to-1884>

[P57]: <https://link.springer.com/article/10.1007/s11138-021-00548-7>

[P56]: <https://www.degruyter.com/document/doi/10.1515/ev-2023-0001/html>

[P55]: <https://onlinelibrary.wiley.com/doi/10.1111/coep.12595>

[P54]: <https://www.independent.org/publications/tir/article.asp?id=1716>

[P53]: <https://www.sciencedirect.com/science/article/pii/S0167268122002025?via%3Dihub>

[P52]: <https://link.springer.com/article/10.1007/s11138-019-00497-2>

[P51]: <http://journal.apee.org/index.php/PARTE1_2021_Journal_of_Private_Enterprise_Vol_36_No_2_Summer>

[P50]: <https://link.springer.com/article/10.1007/s11138-020-00500-1>

[P49]: <https://onlinelibrary.wiley.com/doi/10.1002/soej.12498>

[P48]: <https://www.sciencedirect.com/science/article/abs/pii/S0167268121000408>

[P47]: <https://www.sciencedirect.com/science/article/abs/pii/S106297692100020X>

[P46]: <https://link.springer.com/article/10.1007%2Fs10602-020-09302-w?fbclid=IwAR3lPfONbc7wUGQf8k6jabt-HtjbskOnjSok2Xue4yDexT0yIzfv5tzH1h4>

[P45]: <http://journal.apee.org/index.php?title=2020_Journal_of_Private_Enterprise_Vol_35_No_1_Spring_parte2>

[P44]: <https://link.springer.com/article/10.1007/s11127-020-00819-0>

[P43]: <https://onlinelibrary.wiley.com/doi/abs/10.1002/mde.3133>

[P42]: <https://link.springer.com/article/10.1007/s11138-019-00436-1>

[P41]: <https://www.tandfonline.com/doi/full/10.1080/08853908.2019.1695026>

[P40]: <https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-8454.12158>

[P39]: <https://link.springer.com/article/10.1007/s11138-019-00460-1>

[P38]: <http://www.independent.org/publications/tir/article.asp?id=1416>

[P37]: <https://misesjournal.org.br/misesjournal/article/view/965>

[P36]: <http://journal.apee.org/index.php?title=2018_Journal_of_Private_Enterprise_Vol_33_No_2_Summer_parte2>

[P35]: <https://www.sciencedirect.com/science/article/pii/S0167268118300301?via%3Dihub>

[P34]: <http://link.springer.com/article/10.1007/s11138-016-0374-8>

[P33]: <https://www.cambridge.org/core/journals/journal-of-the-history-of-economic-thought/article/average-period-of-production-the-history-and-rehabilitation-of-an-idea/3B8E09B00DB6150D1041EC0AADF72303>

[P32]: <https://link.springer.com/article/10.1007/s11127-018-0509-5>

[P31]: <https://mises-media.s3.amazonaws.com/Secular%20Growth%20in%20Garrisons%20Model.pdf?file=1&type=document>

[P30]: <http://link.springer.com/article/10.1007%2Fs11138-016-0348-x>

[P29]: <https://www.degruyter.com/view/journals/jbvela/12/s1/article-20160014.xml>

[P28]: <http://journal.apee.org/index.php?title=2017_Journal_of_Private_Enterprise_vol_32_no_2_Summer_parte1.pdf>

[P27]: <http://link.springer.com/article/10.1007%2Fs11138-016-0340-5>

[P26]: <https://mises.org/library/mathematical-version-garrisons-model>

[P24]: <http://journals.cambridge.org/action/displayAbstract?fromPage=online&aid=10361562&fulltextType=RA&fileId=S1744137416000102>

[P23]: <http://www.sciencedirect.com/science/article/pii/S105833001530080X>

[P22]: <http://www.emeraldinsight.com/doi/full/10.1108/JEPP-03-2015-0016>

[P21]: <http://www.emeraldinsight.com/doi/full/10.1108/JFEP-07-2015-0041>

[P20]: <http://www.emeraldinsight.com/doi/abs/10.1108/S1529-213420160000020002>

[P19]: <http://www.sciencedirect.com/science/article/pii/S1062976915000848#>

[P18]: <http://www.tandfonline.com/doi/full/10.1080/1226508X.2015.1137484>

[P17]: <http://journal.apee.org/index.php?title=Parte6_Journal_of_Private_Enterprise_vol_30_no_4.pdf>

[P16]: <https://ideas.repec.org/a/ioe/cuadec/v52y2015i1p95-116.html>

[P15]: <http://link.springer.com/article/10.1007/s11138-014-0267-7>

[P14]: <http://journals.cambridge.org/action/displayAbstract?fromPage=online&aid=9555966&fulltext&fileId=S1053837214000777>

[P13]: <http://www.independent.org/publications/tir/article.asp?a=1032>

[P12]: <http://www.tandfonline.com/doi/full/10.1080/09538259.2014.957475#.VD9ioxY8QXQ>

[P11]: <https://link.springer.com/article/10.1007/s11138-012-0188-2>

[P10]: <http://www.sciencedirect.com/science/article/pii/S1062976914000192>

[P09]: <http://www.omicsgroup.org/journals/hayeks-rule-ngdp-targeting-and-the-productivity-norm-theory-and-application-2168-9458-3-121.pdf>

[P08]: <http://laissezfaire.ufm.edu/index.php?title=LF_38.1&fullscreen=true>

[P07]: <http://www.cevroinstitut.cz/upload/ck/files/Casopisy_clanky/12_05_NPPE_Vol7_06.pdf>

[P06]: <http://www.independent.org/publications/tir/article.asp?a=882>

[P05]: <https://link.springer.com/article/10.1007/s10551-011-0900-3>

[P04]: <http://mises.org/journals/qjae/pdf/qjae14_1_4.pdf>

[P03]: <http://www.cevroinstitut.cz/upload/file/NPPE/NPPE_6_1.pdf>

[P02]: <https://www.eseade.edu.ar/wp-content/uploads/2016/08/52_2_cachanosky.pdf>

[P01]: <http://libertarianpapers.org/articles/2009/lp-1-43.pdf>


<!-- HYPERLINKS TO NON-REFEREED JOURNAL ARTICLES -->
[NRP07]: <https://journallibertas.com/files/2021/6.1%20-%2002%20-%20Cachanosky,%20N.%20-%20The%20Austrian%20School%20%28150%20Years%29.pdf>

[NRP06]: <https://journallibertas.com/files/2021/6.1%20-%2005%20-%20Lewin%20and%20Cachanosky%20-%20Capital%20%28Three%20Dimensionally%20Speaking%29.pdf>

[NRP05]: <http://www.journallibertas.com/uploads/7/4/7/8/7478847/libertas.4.1_-_05.zanotti_and_cachanosky.pdf>

[NRP04]: <http://www.journallibertas.com/uploads/7/4/7/8/7478847/libertas.2.1_-_04.cachanosky_n.___padilla_a..pdf>

[NRP03]: <https://static1.squarespace.com/static/575f50868259b52cea334ff2/t/583f28656b8f5b2d03782196/1480534119094/Sawhney.Kulkarni.Cachanosky.pdf>

[NRP02]: <http://www.journallibertas.com/uploads/7/4/7/8/7478847/libertas.1.2_-_08.cachanosky_nicolas.pdf>

[NRP01]: <http://www.journallibertas.com/uploads/7/4/7/8/7478847/libertas.1.1_-_03.cachanosky_j._c.___cachanosky_n..pdf>


<!-- HYPERLINKS TO BOOK CHAPTERS -->
[BC08]: <https://www.e-elgar.com/shop/usd/a-research-agenda-for-austrian-economics-9781800882256.html>

[BC07]: <https://www.e-elgar.com/shop/usd/the-economics-of-blockchain-and-cryptocurrency-9781800882331.html>

[BC05]: <https://www.springer.com/us/book/9783319758169?msclkid=27b03cb7844b1d1984a867a8448337af&utm_source=bing&utm_medium=cpc&utm_campaign=Shopping%20%7C%20US&utm_term=1101200786988&utm_content=All%20eBooks#aboutBook>

[BC03]: <https://www.amazon.com/Libertad-convicciones-Ensayos-Cachanosky-1953-2015-ebook/dp/B07477VJT8/ref=sr_1_1?ie=UTF8&qid=1503468198&sr=8-1&keywords=juan+cachanosky>

[BC02]: <http://www.amazon.com/Economics-Immigration-Market-Based-Approaches-Science/dp/0190258799/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=>

[BC01]: <http://unioneditorial.es/index.php?page=shop.product_details&flypage=flypage.tpl&product_id=237&category_id=17&option=com_virtuemart&Itemid=22>


<!-- HYPERLINKS TO JOURNAL ARTICLES -->
[WP04]: <https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4932683>

[WP03]: <https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4862007>

[WP02]: <https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4476965>

[WP01]: <https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4437371>


<!-- HYPERLINKS TO CO-AUTHORS -->
<!-- Braun, Eduard -->
[EB]: <https://www.wiwi.tu-clausthal.de/abteilungen/volkswirtschaftslehre/personen/braun/>

<!-- Cutsinger, Bryan -->
[BC]: https://www.bryancutsinger.com/

<!-- Evans, Anthony -->
[AV]: http://econ.anthonyjevans.com/>

<!-- Gomez, Alejandro -->
[AG]: https://ucema.edu.ar/cgi-bin/profesores/listap.pl?id=3451

<!-- Hoffmann, Andreas -->
[AH]: <http://www.a-hoffmann.info/>

<!-- Hogan, Thomas -->
[TH]: https://thomaslhogan.com/

<!-- Lewin, Peter -->
[PL]: <http://www.utdallas.edu/~plewin/>

<!-- Lopez, Edward J. -->
[EJL]: https://faculty.wcu.edu/ejlopez/

<!-- Luther, William -->
[WL]: https://www.williamjluther.com/

<!-- Nair, Malavika -->
[MN]: <http://www.malavikanair.com/>

<!-- Ocampo, Emilio -->
[EO]: <https://ucema.edu.ar/personal/emilio-ocampo>

<!-- Padilla, Alex -->
[AP]: <http://www.alexandrepadilla.com/home>

<!-- Ravier, Adrian -->
[AR]: <http://www.adrianravier.com/>

<!-- Salter, Alex -->
[AS]: <http://www.awsalter.com/>

<!-- Zanotti, Gabriel -->
[GZ]: <http://gabrielzanotti.com/>

<!-- J. P. Bastos -->
[JPB]: <https://www.jpmvbastos.com/>